### ISSUE TITLE
项目似乎缺少config/secret文件

### ISSUE THREAD

**Issue by Ryan-CW-Code** [galaxy-s10/vue3-blog-server#1]
你好，我下载后，使用`yarn install`安装依赖。但是提示检测不到secret模块。根据引用路径是在config/下，但是没有发现

**Comment by galaxy-s10** [comment]
hi，朋友你好，很高兴你能下载这项目，config是缺少了secret.ts，因为我把它忽略了，你可以自己新建这个文件

```ts
export const jwtSecret = 'xxxxxxxxxxxxx'; // jwt秘钥

export const qiniu_accessKey = 'xxxxxxxxxxxxx'; // 七牛云秘钥
export const qiniu_secretKey = 'xxxxxxxxxxxxx'; // 七牛云秘钥
export const qiniu_callBackUrl = 'xxxxxxxxxxxxx'; // 七牛云回调
export const qiniu_backupsDatabase = 'xxxxxxxxxxxxx'; // 七牛云数据库备份目录(开头不能带/)

export const www_qq_client_id = 'xxxxxxxxxxxxx'; // qq登录APP ID
export const www_qq_client_secret = 'xxxxxxxxxxxxx'; // qq登录APP Key
export const www_qq_redirect_uri = 'xxxxxxxxxxxxx'; // qq登录回调地址
export const admin_qq_client_id = 'xxxxxxxxxxxxx'; // qq登录APP ID
export const admin_qq_client_secret = 'xxxxxxxxxxxxx'; // qq登录APP Key
export const admin_qq_redirect_uri = 'xxxxxxxxxxxxx'; // qq登录回调地址

export const github_client_id = 'xxxxxxxxxxxxx'; // github登录APP ID
export const github_client_secret = 'xxxxxxxxxxxxx'; // github登录APP Key
export const github_redirect_uri = 'xxxxxxxxxxxxx'; // github登录回调地址

export const gaode_web_ip_key = 'xxxxxxxxxxxxx'; // 高德地图key

export const qq_email_user = 'xxxxxxxxxxxxx'; // qq邮箱auth的用户
export const qq_email_pass = 'xxxxxxxxxxxxx'; // qq邮箱auth的秘钥

export const mysqlConfig = {
  database: 'xxxxxxxxxxxxx',
  username: 'xxxxxxxxxxxxx',
  password: 'xxxxxxxxxxxxx',
  host: 'xxxxxxxxxxxxx',
  port: 1111111,
};

export const sshConfig = {
  username: 'xxxxxxxxxxxxx',
  password: 'xxxxxxxxxxxxx',
  host: 'xxxxxxxxxxxxx',
  port: 11111111,
};

```

**Comment by Ryan-CW-Code** [comment]
感谢你的回复，我是嵌入式程序员希望了解些前端知识，使用vue3和koa2做过后台管理系统，想学习这个博客项目。api文档可以给参考吗？

**Comment by galaxy-s10** [comment]
暂时没有提供api文档（后续有可能会提供），你可以再这里控制台看看网络，https://www.hsslive.cn

**Comment by galaxy-s10** [comment]
> 感谢你的回复，我是嵌入式程序员希望了解些前端知识，使用vue3和koa2做过后台管理系统，想学习这个博客项目。api文档可以给参考吗？

hey老兄，最近可能会写接口文档（apifox），可以关注：https://www.apifox.cn/apidoc/shared-e73bb55d-ccdd-40a2-ab41-961e1ffcfa10/api-14831602

**Comment by Ryan-CW-Code** [comment]
> > 谢谢你的回复，我是一个嵌入式工程师希望了解一些前端知识，使用 3 和 ko2 学习项目后台管理系统，想这个。api文档可以给参考吗？
> 
> 嘿老兄，最近可能会写接口文档（apifox），可以关注：[https ://www.apifox.cn/apidoc/shared-e73bb55d-ccdd-40a2-ab41-961e1ffcfa10/api-14831602](https://www.apifox.cn/apidoc/shared-e73bb55d-ccdd-40a2-ab41-961e1ffcfa10/api-14831602)

好耶谢谢，我在尝试根据已有代码进行注册用户，但使用post请求注册需要先登录用户，直接在数据库添加似乎有很多外键关联，依然无法登录。期待你的接口文档

**Comment by galaxy-s10** [comment]
> > > 谢谢你的回复，我是一个嵌入式工程师希望了解一些前端知识，使用 3 和 ko2 学习项目后台管理系统，想这个。api文档可以给参考吗？
> > 
> > 
> > 嘿老兄，最近可能会写接口文档（apifox），可以关注：[https ://www.apifox.cn/apidoc/shared-e73bb55d-ccdd-40a2-ab41-961e1ffcfa10/api-14831602](https://www.apifox.cn/apidoc/shared-e73bb55d-ccdd-40a2-ab41-961e1ffcfa10/api-14831602)
> 
> 好耶谢谢，我在尝试根据已有代码进行注册用户，但使用post请求注册需要先登录用户，直接在数据库添加似乎有很多外键关联，依然无法登录。期待你的接口文档

嗯，应该还有些问题，最近会整理
