### ISSUE TITLE
请问数据库是不会 自动建表的吗

### ISSUE THREAD

**Issue by CodeRookie262** [galaxy-s10/vue3-blog-server#7]
@galaxy-s10 请问大佬一个问题。

操作步骤：
1. admin 注册用户，输入邮箱验证码后点击注册
2. server 报错如下
![image](https://github.com/galaxy-s10/vue3-blog-server/assets/41562303/ec9e4070-50db-4dde-ac1f-73021d7f869e)

源码：
![image](https://github.com/galaxy-s10/vue3-blog-server/assets/41562303/0b2c3a58-90c7-4c04-86c8-eca9ebdd1706)

**Comment by galaxy-s10** [comment]
前几天可能改出问题了，找时间我再看看

**Comment by CodeRookie262** [comment]
> 前几天可能改出问题了，找时间我再看看

大佬，我强制执行表创建后，用户邮箱注册成功了，但是登录过程中提示没有角色，roles是空数组。
